### ISSUE TITLE
kubectl apply -f /srv/addons/apiserver-to-kubelet-rbac.yml 报错

### ISSUE THREAD

**Issue by zhsh87** [unixhot/kube-salt#12]
/srv/addons/apiserver-to-kubelet-rbac.yml
这个文件里边多出一段脚本

[root@kube-master37 yaml]# kubectl apply -f apiserver-to-kubelet-rbac.yml ^C
[root@kube-master37 yaml]# cat apiserver-to-kubelet-rbac.yml

**Comment by unixhot** [comment]
收到，之前合并时为仔细检查。
